name: 刷步数

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 2 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 开始 账号 1
      run: |
        user='${{ secrets.USER1 }}'
        pwd='${{ secrets.PWD1 }}'
        step='${{ secrets.STEP }}'
        
        python3 main.py <<EOF
        ${sckey}
        ${user}
        ${pwd}
        ${step}
        EOF
    - name: 开始 账号 2
      run: |
        user='${{ secrets.USER2 }}'
        pwd='${{ secrets.PWD2 }}'
        step='${{ secrets.STEP }}'
        
        python3 main.py <<EOF
        ${sckey}
        ${user}
        ${pwd}
        ${step}
        EOF
    - name: 开始 账号 3
      run: |
        user='${{ secrets.USER3 }}'
        pwd='${{ secrets.PWD3 }}'
        step='${{ secrets.STEP }}'
        
        python3 main.py <<EOF
        ${sckey}
        ${user}
        ${pwd}
        ${step}
        EOF
